### ISSUE TITLE
Version Django

### ISSUE THREAD

**Issue by pyjavo** [neosergio/recetario_mdw#1]
Hola Sergio!

Excelentes explicaciones las de tu tutorial. Estuve checando el ejemplo de recetario pero no estoy seguro que versión de Django. Sería bueno que colocaras un requirements.txt con la version de Django para probarlo en un virtualenv.

Saludos y gracias.

**Comment by neosergio** [comment]
Hola Javier

Gracias por la recomendación, la verdad iba a dejarlo con el contenido totalmente basico como el curso, pero me he animado ha actualizarlo despues de varios años, ha agregarle algunas cosas mas como requerimientos y actualizarlo a una version mas reciente.

Ya esta el requirements.txt en el siguiente commit https://github.com/neosergio/recetario_mdw/commit/5fc17e7c232be4f7c3eb72999acaaab9b5ad72b9

Un saludo
