### ISSUE TITLE
Server Error (500)

### ISSUE THREAD

**Issue by wuilmerbolivar** [neosergio/recetario_mdw#2]
Si realizo estos pasos:

DEBUG = True
TEMPLATE_DEBUG = DEBUG

ADMINS = (
                ('Sergio Infante Montero', 'raulsergio9@gmail.com'),
)

Me da error: Server Error (500)

Si paso DEBUG = False, se soluciona el problema.
Creo se debe realizar una observación al respecto.

Linea: https://github.com/neosergio/recetario_mdw/blob/master/recetario/recetario/settings.py#L10

**Comment by neosergio** [comment]
Estoy actualizando todo el proyecto a la versión Django 1.10.5. El proyecto anterior quedo obsoleto hace muchos años atras.
